package requests

type Item struct {
	ProductionOrderConfirmation		 							int		 `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem		 						int		 `json:"ProductionOrderConfirmationItem"`
	PrecedingProductionOrderConfirmationItem					int		 `json:"PrecedingProductionOrderConfirmationItem"`
	FollowingProductionOrderConfirmationItem					int		 `json:"FollowingProductionOrderConfirmationItem"`
	SupplyChainRelationshipID									int		 `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipProductionPlantID					int		 `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipDeliveryID							int		 `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID						int		 `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionOrderConfirmationType								string	 `json:"ProductionOrderConfirmationType"`
	Product														string	 `json:"Product"`
	Buyer														int		 `json:"Buyer"`
	Seller														int		 `json:"Seller"`
	ProductionPlantBusinessPartner								int		 `json:"ProductionPlantBusinessPartner"`
	ProductionPlant												string	 `json:"ProductionPlant"`
	ProductionPlantStorageLocation								string	 `json:"ProductionPlantStorageLocation"`
	DeliverToParty												int		 `json:"DeliverToParty"`
	DeliverToPlant												string	 `json:"DeliverToPlant"`
	DeliverToPlantStorageLocation								string	 `json:"DeliverToPlantStorageLocation"`
	DeliverFromParty											int		 `json:"DeliverFromParty"`
	DeliverFromPlant											string	 `json:"DeliverFromPlant"`
	DeliverFromPlantStorageLocation								string	 `json:"DeliverFromPlantStorageLocation"`
	MRPArea														*string	 `json:"MRPArea"`
	MRPController												*string	 `json:"MRPController"`
	ProductionVersion											*int	 `json:"ProductionVersion"`
	ProductionVersionItem										*int	 `json:"ProductionVersionItem"`
	BillOfMaterial												int		 `json:"BillOfMaterial"`
	Operations													int		 `json:"Operations"`
	ProductionOrderConfirmationQuantityInBaseUnit				float32	 `json:"ProductionOrderConfirmationQuantityInBaseUnit"`
	ProductionOrderConfirmationQuantityInProductionUnit			float32	 `json:"ProductionOrderConfirmationQuantityInProductionUnit"`
	ProductionOrderConfirmationQuantityInDeliveryUnit			float32	 `json:"ProductionOrderConfirmationQuantityInDeliveryUnit"`
	ProductionOrderConfirmationPlannedScrapQtyInBaseUnit		*float32 `json:"ProductionOrderConfirmationPlannedScrapQtyInBaseUnit"`
	ProductionOrderConfirmationMinimumLotSizeQuantity			float32	 `json:"ProductionOrderConfirmationMinimumLotSizeQuantity"`
	ProductionOrderConfirmationStandardLotSizeQuantity			float32	 `json:"ProductionOrderConfirmationStandardLotSizeQuantity"`
	ProductionOrderConfirmationMaximumLotSizeQuantity			float32	 `json:"ProductionOrderConfirmationMaximumLotSizeQuantity"`
	ProductionOrderConfirmationLotSizeRoundingQuantity			*float32 `json:"ProductionOrderConfirmationLotSizeRoundingQuantity"`
	ProductionOrderConfirmationLotSizeIsFixed					*bool	 `json:"ProductionOrderConfirmationLotSizeIsFixed"`
	ProductionOrderConfirmationPlannedStartDate					string	 `json:"ProductionOrderConfirmationPlannedStartDate"`
	ProductionOrderConfirmationPlannedStartTime					string	 `json:"ProductionOrderConfirmationPlannedStartTime"`
	ProductionOrderConfirmationPlannedEndDate					string	 `json:"ProductionOrderConfirmationPlannedEndDate"`
	ProductionOrderConfirmationPlannedEndTime					string	 `json:"ProductionOrderConfirmationPlannedEndTime"`
	ProductionOrderConfirmationActualReleaseDate				*string	 `json:"ProductionOrderConfirmationActualReleaseDate"`
	ProductionOrderConfirmationActualReleaseTime				*string	 `json:"ProductionOrderConfirmationActualReleaseTime"`
	ProductionOrderConfirmationActualStartDate					*string	 `json:"ProductionOrderConfirmationActualStartDate"`
	ProductionOrderConfirmationActualStartTime					*string	 `json:"ProductionOrderConfirmationActualStartTime"`
	ProductionOrderConfirmationActualEndDate					*string	 `json:"ProductionOrderConfirmationActualEndDate"`
	ProductionOrderConfirmationActualEndTime					*string	 `json:"ProductionOrderConfirmationActualEndTime"`
	ConfirmedYieldQuantityInBaseUnit							*float32 `json:"ConfirmedYieldQuantityInBaseUnit"`
	ConfirmedYieldQuantityInProductionUnit						*float32 `json:"ConfirmedYieldQuantityInProductionUnit"`
	ScrappedQuantityInBaseUnit									*float32 `json:"ScrappedQuantityInBaseUnit"`
	PlannedOrder												*int	 `json:"PlannedOrder"`
	PlannedOrderItem											*int	 `json:"PlannedOrderItem"`
	OrderID														*int	 `json:"OrderID"`
	OrderItem													*int	 `json:"OrderItem"`
	ProductIsBatchManagedInProductionPlant						*bool	 `json:"ProductIsBatchManagedInProductionPlant"`
	BatchMgmtPolicyInProductionOrderConfirmation				*string	 `json:"BatchMgmtPolicyInProductionOrderConfirmation"`
	ProductionOrderConfirmationTargetedBatch					*string  `json:"ProductionOrderConfirmationTargetedBatch"`
	ProductionOrderConfirmationTargetedBatchValidityStartDate	*string	 `json:"ProductionOrderConfirmationTargetedBatchValidityStartDate"`
	ProductionOrderConfirmationTargetedBatchValidityStartTime	*string	 `json:"ProductionOrderConfirmationTargetedBatchValidityStartTime"`
	ProductionOrderConfirmationTargetedBatchValidityEndDate		*string	 `json:"ProductionOrderConfirmationTargetedBatchValidityEndDate"`
	ProductionOrderConfirmationTargetedBatchValidityEndTime		*string	 `json:"ProductionOrderConfirmationTargetedBatchValidityEndTime"`
	ProductionOrderConfirmationItemText							*string	 `json:"ProductionOrderConfirmationItemText"`
	CreationDate												string	 `json:"CreationDate"`
	CreationTime												string	 `json:"CreationTime"`
	LastChangeDate												string	 `json:"LastChangeDate"`
	LastChangeTime												string	 `json:"LastChangeTime"`
	IsReleased													*bool	 `json:"IsReleased"`
	IsPartiallyConfirmed										*bool	 `json:"IsPartiallyConfirmed"`
	IsConfirmed													*bool	 `json:"IsConfirmed"`
	IsLocked													*bool	 `json:"IsLocked"`
	IsCancelled													*bool	 `json:"IsCancelled"`
	IsMarkedForDeletion											*bool	 `json:"IsMarkedForDeletion"`
}
