package dpfm_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	ProductionOrderConfirmation struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"business_partner"`
	APISchema     string   `json:"api_schema"`
	Accepter      []string `json:"accepter"`
	MaterialCode  string   `json:"material_code"`
	Plant         string   `json:"plant/supplier"`
	Stock         string   `json:"stock"`
	DocumentType  string   `json:"document_type"`
	DocumentNo    string   `json:"document_no"`
	PlannedDate   string   `json:"planned_date"`
	ValidatedDate string   `json:"validated_date"`
	Deleted       bool     `json:"deleted"`
}

type SDC struct {
	ConnectionKey     string          `json:"connection_key"`
	Result            bool            `json:"result"`
	RedisKey          string          `json:"redis_key"`
	Filepath          string          `json:"filepath"`
	APIStatusCode     int             `json:"api_status_code"`
	RuntimeSessionID  string          `json:"runtime_session_id"`
	BusinessPartnerID *int            `json:"business_partner"`
	ServiceLabel      string          `json:"service_label"`
	APIType           string          `json:"api_type"`
	InputParameters   InputParameters `json:"InputParameters"`
	Header            Header          `json:"ProductionOrderConfirmation"`
	APISchema         string          `json:"api_schema"`
	Accepter          []string        `json:"accepter"`
	Deleted           bool            `json:"deleted"`
}

type InputParameters struct {
	MRPArea                                 *[]*string `json:"MRPArea"`
	MRPAreaTo                               *string    `json:"MRPAreaTo"`
	MRPAreaFrom                             *string    `json:"MRPAreaFrom"`
	OwnerProductionPlantBusinessPartner     *[]*int    `json:"OwnerProductionPlantBusinessPartner"`
	OwnerProductionPlantBusinessPartnerTo   *int       `json:"OwnerProductionPlantBusinessPartnerTo"`
	OwnerProductionPlantBusinessPartnerFrom *int       `json:"OwnerProductionPlantBusinessPartnerFrom"`
	OwnerProductionPlant                    *[]*string `json:"OwnerProductionPlant"`
	OwnerProductionPlantTo                  *string    `json:"OwnerProductionPlantTo"`
	OwnerProductionPlantFrom                *string    `json:"OwnerProductionPlantFrom"`
	ProductInHeader                         *[]*string `json:"ProductInHeader"`
	ProductInHeaderTo                       *string    `json:"ProductInHeaderTo"`
	ProductInHeaderFrom                     *string    `json:"ProductInHeaderFrom"`
	ProductInItem                           *[]*string `json:"ProductInItem"`
	ProductInItemTo                         *string    `json:"ProductInItemTo"`
	ProductInItemFrom                       *string    `json:"ProductInItemFrom"`
	ProductionPlantBusinessPartner          *[]*int    `json:"ProductionPlantBusinessPartner"`
	ProductionPlantBusinessPartnerTo        *int       `json:"ProductionPlantBusinessPartnerTo"`
	ProductionPlantBusinessPartnerFrom      *int       `json:"ProductionPlantBusinessPartnerFrom"`
	ProductionPlant                         *[]*string `json:"ProductionPlant"`
	ProductionPlantTo                       *string    `json:"ProductionPlantTo"`
	ProductionPlantFrom                     *string    `json:"ProductionPlantFrom"`
	ProductionPlantStorageLocation          *[]*string `json:"ProductionPlantStorageLocation"`
	ProductionPlantStorageLocationTo        *string    `json:"ProductionPlantStorageLocationTo"`
	ProductionPlantStorageLocationFrom      *string    `json:"ProductionPlantStorageLocationFrom"`
	ExecuteProductAvailabilityCheck         *bool      `json:"ExecuteProductAvailabilityCheck"`
	ReleaseProductionOrderConfirmation      *bool      `json:"ReleaseProductionOrderConfirmation"`
}

type Header struct {
	ProductionOrder                          int      `json:ProductionOrder`
	ProductionOrderItem                      int      `json:ProductionOrderItem`
	Operations                               int      `json:Operations`
	OperationsItem                           int      `json:OperationsItem`
	OperationID                              int      `json:OperationID`
	ConfirmationCountingID                   int      `json:ConfirmationCountingID`
	OperationPlannedQuantityInBaseUnit       *float32 `json:OperationPlannedQuantityInBaseUnit`
	OperationPlannedQuantityInProductionUnit *float32 `json:OperationPlannedQuantityInProductionUnit`
	OperationPlannedQuantityInOperationUnit  *float32 `json:OperationPlannedQuantityInOperationUnit`
	ProductBaseUnit                          *string  `json:ProductBaseUnit`
	ProductProductionUnit                    *string  `json:ProductProductionUnit`
	ProductOperationUnit                     *string  `json:ProductOperationUnit`
	OperationPlannedScrapInPercent           *float32 `json:OperationPlannedScrapInPercent`
	ConfirmationEntryDate                    *string  `json:ConfirmationEntryDate`
	ConfirmationEntryTime                    *string  `json:ConfirmationEntryTime`
	ConfirmationText                         *string  `json:ConfirmationText`
	IsFinalConfirmation                      *string  `json:IsFinalConfirmation`
	WorkCenter                               *int     `json:WorkCenter`
	EmployeeIDWhoConfirmed                   *int     `json:EmployeeIDWhoConfirmed`
	ConfirmedExecutionStartDate              *string  `json:ConfirmedExecutionStartDate`
	ConfirmedExecutionStartTime              *string  `json:ConfirmedExecutionStartTime`
	ConfirmedSetupStartDate                  *string  `json:ConfirmedSetupStartDate`
	ConfirmedSetupStartTime                  *string  `json:ConfirmedSetupStartTime`
	ConfirmedProcessingStartDate             *string  `json:ConfirmedProcessingStartDate`
	ConfirmedProcessingStartTime             *string  `json:ConfirmedProcessingStartTime`
	ConfirmedExecutionEndDate                *string  `json:ConfirmedExecutionEndDate`
	ConfirmedExecutionEndTime                *string  `json:ConfirmedExecutionEndTime`
	ConfirmedSetupEndDate                    *string  `json:ConfirmedSetupEndDate`
	ConfirmedSetupEndTime                    *string  `json:ConfirmedSetupEndTime`
	ConfirmedProcessingEndDate               *string  `json:ConfirmedProcessingEndDate`
	ConfirmedProcessingEndTime               *string  `json:ConfirmedProcessingEndTime`
	ConfirmedWaitDuration                    *float32 `json:ConfirmedWaitDuration`
	WaitDurationUnit                         *string  `json:WaitDurationUnit`
	ConfirmedQueueDuration                   *float32 `json:ConfirmedQueueDuration`
	QueueDurationUnit                        *string  `json:QueueDurationUnit`
	ConfirmedMoveDuration                    *float32 `json:ConfirmedMoveDuration`
	MoveDurationUnit                         *string  `json:MoveDurationUnit`
	ConfirmedYieldQuantity                   *float32 `json:ConfirmedYieldQuantity`
	ConfirmedScrapQuantity                   *float32 `json:ConfirmedScrapQuantity`
	OperationVarianceReason                  *string  `json:OperationVarianceReason`
	CreationDate                             *string  `json:CreationDate`
	CreationTime                             *string  `json:CreationTime`
	LastChangeDate                           *string  `json:LastChangeDate`
	LastChangeTime                           *string  `json:LastChangeTime`
	IsCancelled                              *int     `json:IsCancelled`
}

type HeaderDoc struct {
	ProductionOrder          int     `json:ProductionOrder`
	ProductionOrderItem      int     `json:ProductionOrderItem`
	Operations               int     `json:Operations`
	OperationsItem           int     `json:OperationsItem`
	OperationID              int     `json:OperationID`
	ConfirmationCountingID   int     `json:ConfirmationCountingID`
	DocType                  string  `json:DocType`
	DocVersionID             int     `json:DocVersionID`
	DocID                    string  `json:DocID`
	FileExtension            *string `json:FileExtension`
	FileName                 *string `json:FileName`
	FilePath                 *string `json:FilePath`
	DocIssuerBusinessPartner *int    `json:DocIssuerBusinessPartner`
}

type Item struct {
	ProductionOrderConfirmation                               int             `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem                           int             `json:"ProductionOrderConfirmationItem"`
	PrecedingProductionOrderConfirmationItem                  *int            `json:"PrecedingProductionOrderConfirmationItem"`
	FollowingProductionOrderConfirmationItem                  *int            `json:"FollowingProductionOrderConfirmationItem"`
	SupplyChainRelationshipID                                 *int            `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipProductionPlantID                  *int            `json:"SupplyChainRelationshipProductionPlantID"`
	SupplyChainRelationshipDeliveryID                         *int            `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID                    *int            `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionOrderConfirmationType                           *string         `json:"ProductionOrderConfirmationType"`
	Product                                                   *string         `json:"Product"`
	Buyer                                                     *int            `json:"Buyer"`
	Seller                                                    *int            `json:"Seller"`
	ProductionPlantBusinessPartner                            *int            `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                           *string         `json:"ProductionPlant"`
	ProductionPlantStorageLocation                            *string         `json:"ProductionPlantStorageLocation"`
	DeliverToParty                                            *int            `json:"DeliverToParty"`
	DeliverToPlant                                            *string         `json:"DeliverToPlant"`
	DeliverToPlantStorageLocation                             *string         `json:"DeliverToPlantStorageLocation"`
	DeliverFromParty                                          *int            `json:"DeliverFromParty"`
	DeliverFromPlant                                          *string         `json:"DeliverFromPlant"`
	DeliverFromPlantStorageLocation                           *string         `json:"DeliverFromPlantStorageLocation"`
	MRPArea                                                   *string         `json:"MRPArea"`
	MRPController                                             *string         `json:"MRPController"`
	ProductionVersion                                         *int            `json:"ProductionVersion"`
	ProductionVersionItem                                     *int            `json:"ProductionVersionItem"`
	BillOfMaterial                                            *int            `json:"BillOfMaterial"`
	Operations                                                *int            `json:"Operations"`
	ProductionOrderConfirmationQuantityInBaseUnit             *float32        `json:"ProductionOrderConfirmationQuantityInBaseUnit"`
	ProductionOrderConfirmationQuantityInProductionUnit       *float32        `json:"ProductionOrderConfirmationQuantityInProductionUnit"`
	ProductionOrderConfirmationQuantityInDeliveryUnit         *float32        `json:"ProductionOrderConfirmationQuantityInDeliveryUnit"`
	ProductionOrderConfirmationPlannedScrapQtyInBaseUnit      *float32        `json:"ProductionOrderConfirmationPlannedScrapQtyInBaseUnit"`
	ProductionOrderConfirmationMinimumLotSizeQuantity         *float32        `json:"ProductionOrderConfirmationMinimumLotSizeQuantity"`
	ProductionOrderConfirmationStandardLotSizeQuantity        *float32        `json:"ProductionOrderConfirmationStandardLotSizeQuantity"`
	ProductionOrderConfirmationMaximumLotSizeQuantity         *float32        `json:"ProductionOrderConfirmationMaximumLotSizeQuantity"`
	ProductionOrderConfirmationLotSizeRoundingQuantity        *float32        `json:"ProductionOrderConfirmationLotSizeRoundingQuantity"`
	ProductionOrderConfirmationLotSizeIsFixed                 *bool           `json:"ProductionOrderConfirmationLotSizeIsFixed"`
	ProductionOrderConfirmationPlannedStartDate               *string         `json:"ProductionOrderConfirmationPlannedStartDate"`
	ProductionOrderConfirmationPlannedStartTime               *string         `json:"ProductionOrderConfirmationPlannedStartTime"`
	ProductionOrderConfirmationPlannedEndDate                 *string         `json:"ProductionOrderConfirmationPlannedEndDate"`
	ProductionOrderConfirmationPlannedEndTime                 *string         `json:"ProductionOrderConfirmationPlannedEndTime"`
	ProductionOrderConfirmationActualReleaseDate              *string         `json:"ProductionOrderConfirmationActualReleaseDate"`
	ProductionOrderConfirmationActualReleaseTime              *string         `json:"ProductionOrderConfirmationActualReleaseTime"`
	ProductionOrderConfirmationActualStartDate                *string         `json:"ProductionOrderConfirmationActualStartDate"`
	ProductionOrderConfirmationActualStartTime                *string         `json:"ProductionOrderConfirmationActualStartTime"`
	ProductionOrderConfirmationActualEndDate                  *string         `json:"ProductionOrderConfirmationActualEndDate"`
	ProductionOrderConfirmationActualEndTime                  *string         `json:"ProductionOrderConfirmationActualEndTime"`
	ConfirmedYieldQuantityInBaseUnit                          *float32        `json:"ConfirmedYieldQuantityInBaseUnit"`
	ConfirmedYieldQuantityInProductionUnit                    *float32        `json:"ConfirmedYieldQuantityInProductionUnit"`
	ScrappedQuantityInBaseUnit                                *float32        `json:"ScrappedQuantityInBaseUnit"`
	PlannedOrder                                              *int            `json:"PlannedOrder"`
	PlannedOrderItem                                          *int            `json:"PlannedOrderItem"`
	OrderID                                                   *int            `json:"OrderID"`
	OrderItem                                                 *int            `json:"OrderItem"`
	ProductIsBatchManagedInProductionPlant                    *bool           `json:"ProductIsBatchManagedInProductionPlant"`
	BatchMgmtPolicyInProductionOrderConfirmation              *string         `json:"BatchMgmtPolicyInProductionOrderConfirmation"`
	ProductionOrderConfirmationTargetedBatch                  *string         `json:"ProductionOrderConfirmationTargetedBatch"`
	ProductionOrderConfirmationTargetedBatchValidityStartDate *string         `json:"ProductionOrderConfirmationTargetedBatchValidityStartDate"`
	ProductionOrderConfirmationTargetedBatchValidityStartTime *string         `json:"ProductionOrderConfirmationTargetedBatchValidityStartTime"`
	ProductionOrderConfirmationTargetedBatchValidityEndDate   *string         `json:"ProductionOrderConfirmationTargetedBatchValidityEndDate"`
	ProductionOrderConfirmationTargetedBatchValidityEndTime   *string         `json:"ProductionOrderConfirmationTargetedBatchValidityEndTime"`
	ProductionOrderConfirmationItemText                       *string         `json:"ProductionOrderConfirmationItemText"`
	CreationDate                                              *string         `json:"CreationDate"`
	CreationTime                                              *string         `json:"CreationTime"`
	LastChangeDate                                            *string         `json:"LastChangeDate"`
	LastChangeTime                                            *string         `json:"LastChangeTime"`
	IsReleased                                                *bool           `json:"IsReleased"`
	IsPartiallyConfirmed                                      *bool           `json:"IsPartiallyConfirmed"`
	IsConfirmed                                               *bool           `json:"IsConfirmed"`
	IsLocked                                                  *bool           `json:"IsLocked"`
	IsCancelled                                               *bool           `json:"IsCancelled"`
	IsMarkedForDeletion                                       *bool           `json:"IsMarkedForDeletion"`
	ItemComponent                                             []ItemComponent `json:"ItemComponent"`
	ItemOperation                                             []ItemOperation `json:"ItemOperation"`
	ItemDoc                                                   []ItemDoc       `json:"ItemDoc"`
}

type ItemComponent struct {
	ProductionOrderConfirmation                    int                                 `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem                int                                 `json:"ProductionOrderConfirmationItem"`
	BillOfMaterial                                 int                                 `json:"BillOfMaterial"`
	BillOfMaterialItem                             int                                 `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                      *int                                `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID              *int                                `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID         *int                                `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipStockConfPlantID        *int                                `json:"SupplyChainRelationshipStockConfPlantID"`
	ProductionPlantBusinessPartner                 *int                                `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                *string                             `json:"ProductionPlant"`
	MRPArea                                        *string                             `json:"MRPArea"`
	MRPController                                  *string                             `json:"MRPController"`
	ProductionVersion                              *int                                `json:"ProductionVersion"`
	ProductionVersionItem                          *int                                `json:"ProductionVersionItem"`
	ComponentProduct                               *string                             `json:"ComponentProduct"`
	ComponentProductBuyer                          *int                                `json:"ComponentProductBuyer"`
	ComponentProductSeller                         *int                                `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                 *int                                `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                 *string                             `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty               *int                                `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant               *string                             `json:"ComponentProductDeliverFromPlant"`
	ComponentProductBaseUnit                       *string                             `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                   *string                             `json:"ComponentProductDeliveryUnit"`
	ComponentProductRequirementDate                *string                             `json:"ComponentProductRequirementDate"`
	ComponentProductRequirementTime                *string                             `json:"ComponentProductRequirementTime"`
	ComponentProductRequiredQuantityInBaseUnit     *float32                            `json:"ComponentProductRequiredQuantityInBaseUnit"`
	ComponentProductRequiredQuantityInDeliveryUnit *float32                            `json:"ComponentProductRequiredQuantityInDeliveryUnit"`
	ComponentProductPlannedScrapInPercent          *float32                            `json:"ComponentProductPlannedScrapInPercent"`
	ComponentProductIsMarkedForBackflush           *bool                               `json:"ComponentProductIsMarkedForBackflush"`
	StockConfirmationBusinessPartner               *int                                `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                         *string                             `json:"StockConfirmationPlant"`
	StockConfirmationPlantStorageLocation          *string                             `json:"StockConfirmationPlantStorageLocation"`
	PlannedOrder                                   *int                                `json:"PlannedOrder"`
	PlannedOrderItem                               *int                                `json:"PlannedOrderItem"`
	BillOfMaterialItemText                         *string                             `json:"BillOfMaterialItemText"`
	ComponentProductBatch                          *string                             `json:"ComponentProductBatch"`
	ComponentProductBatchValidityStartDate         *string                             `json:"ComponentProductBatchValidityStartDate"`
	ComponentProductBatchValidityStartTime         *string                             `json:"ComponentProductBatchValidityStartTime"`
	ComponentProductBatchValidityEndDate           *string                             `json:"ComponentProductBatchValidityEndDate"`
	ComponentProductBatchValidityEndTime           *string                             `json:"ComponentProductBatchValidityEndTime"`
	ComponentProductCostingPolicy                  *string                             `json:"ComponentProductCostingPolicy"`
	ComponentProductPriceUnitQty                   *int                                `json:"ComponentProductPriceUnitQty"`
	ComponentProductStandardPrice                  *float32                            `json:"ComponentProductStandardPrice"`
	ComponentProductMovingAveragePrice             *float32                            `json:"ComponentProductMovingAveragePrice"`
	ComponentProductWithdrawnQuantity              *float32                            `json:"ComponentProductWithdrawnQuantity"`
	CreationDate                                   *string                             `json:"CreationDate"`
	CreationTime                                   *string                             `json:"CreationTime"`
	LastChangeDate                                 *string                             `json:"LastChangeDate"`
	LastChangeTime                                 *string                             `json:"LastChangeTime"`
	ComponentProductAvailabilityIsNotChecked       *bool                               `json:"ComponentProductAvailabilityIsNotChecked"`
	IsReleased                                     *bool                               `json:"IsReleased"`
	IsLocked                                       *bool                               `json:"IsLocked"`
	IsCancelled                                    *bool                               `json:"IsCancelled"`
	IsMarkedForDeletion                            *bool                               `json:"IsMarkedForDeletion"`
	ItemComponentDeliveryScheduleLine              []ItemComponentDeliveryScheduleLine `json:"ItemComponentDeliveryScheduleLine"`
	ItemComponentCosting                           []ItemComponentCosting              `json:"ItemComponentCosting"`
}

type ItemComponentDeliveryScheduleLine struct {
	ProductionOrderConfirmation                int      `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem            int      `json:"ProductionOrderConfirmationItem"`
	BillOfMaterial                             int      `json:"BillOfMaterial"`
	BillOfMaterialItem                         int      `json:"BillOfMaterialItem"`
	ScheduleLine                               int      `json:"ScheduleLine"`
	SupplyChainRelationshipID                  *int     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipStockConfPlantID    *int     `json:"SupplyChainRelationshipStockConfPlantID"`
	ComponentProduct                           *string  `json:"ComponentProduct"`
	StockConfirmationBusinessPartner           *int     `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                     *int     `json:"StockConfirmationPlant"`
	StockConfirmationPlantTimeZone             *string  `json:"StockConfirmationPlantTimeZone"`
	ComponentProductBatch                      *string  `json:"ComponentProductBatch"`
	ComponentProductBatchValidityStartDate     *string  `json:"ComponentProductBatchValidityStartDate"`
	ComponentProductBatchValidityStartTime     *string  `json:"ComponentProductBatchValidityStartTime"`
	ComponentProductBatchValidityEndDate       *string  `json:"ComponentProductBatchValidityEndDate"`
	ComponentProductBatchValidityEndTime       *string  `json:"ComponentProductBatchValidityEndTime"`
	RequestedDeliveryDate                      *string  `json:"RequestedDeliveryDate"`
	RequestedDeliveryTime                      *string  `json:"RequestedDeliveryTime"`
	ConfirmedDeliveryDate                      *string  `json:"ConfirmedDeliveryDate"`
	ConfirmedDeliveryTime                      *string  `json:"ConfirmedDeliveryTime"`
	OriginalRequiredQuantityInBaseUnit         *float32 `json:"OriginalRequiredQuantityInBaseUnit"`
	ConfirmedQuantityByPDTAvailCheckInBaseUnit *float32 `json:"ConfirmedQuantityByPDTAvailCheckInBaseUnit"`
	OpenConfirmedQuantityInBaseUnit            *float32 `json:"OpenConfirmedQuantityInBaseUnit"`
	DeliveredQuantityInBaseUnit                *float32 `json:"DeliveredQuantityInBaseUnit"`
	UndeliveredQuantityInBaseUnit              *float32 `json:"UndeliveredQuantityInBaseUnit"`
	StockIsFullyConfirmed                      *bool    `json:"StockIsFullyConfirmed"`
	PlusMinusFlag                              *string  `json:"PlusMinusFlag"`
	ItemScheduleLineDeliveryBlockStatus        *bool    `json:"ItemScheduleLineDeliveryBlockStatus"`
	CreationDate                               *string  `json:"CreationDate"`
	CreationTime                               *string  `json:"CreationTime"`
	LastChangeDate                             *string  `json:"LastChangeDate"`
	LastChangeTime                             *string  `json:"LastChangeTime"`
	IsReleased                                 *bool    `json:"IsReleased"`
	IsLocked                                   *bool    `json:"IsLocked"`
	IsCancelled                                *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                        *bool    `json:"IsMarkedForDeletion"`
}

type ItemComponentCosting struct {
	ProductionOrderConfirmation     int      `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem int      `json:"ProductionOrderConfirmationItem"`
	BillOfMaterial                  int      `json:"BillOfMaterial"`
	BillOfMaterialItem              int      `json:"BillOfMaterialItem"`
	Currency                        *string  `json:"Currency"`
	CostingAmount                   *float32 `json:"CostingAmount"`
	CreationDate                    string   `json:"CreationDate"`
	CreationTime                    string   `json:"CreationTime"`
	LastChangeDate                  string   `json:"LastChangeDate"`
	LastChangeTime                  string   `json:"LastChangeTime"`
	IsReleased                      *bool    `json:"IsReleased"`
	IsLocked                        *bool    `json:"IsLocked"`
	IsCancelled                     *bool    `json:"IsCancelled"`
	IsMarkedForDeletion             *bool    `json:"IsMarkedForDeletion"`
}

type ItemDoc struct {
	ProductionOrderConfirmation     int     `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem int     `json:"ProductionOrderConfirmationItem"`
	DocType                         string  `json:"DocType"`
	DocVersionID                    int     `json:"DocVersionID"`
	DocID                           string  `json:"DocID"`
	FileExtension                   string  `json:"FileExtension"`
	FileName                        *string `json:"FileName"`
	FilePath                        *string `json:"FilePath"`
	DocIssuerBusinessPartner        *int    `json:"DocIssuerBusinessPartner"`
}

type ItemOperation struct {
	ProductionOrderConfirmation                     int                      `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem                 int                      `json:"ProductionOrderConfirmationItem"`
	Operations                                      int                      `json:"Operations"`
	OperationsItem                                  int                      `json:"OperationsItem"`
	OperationID                                     int                      `json:"OperationID"`
	SupplyChainRelationshipID                       *int                     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID               *int                     `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID          *int                     `json:"SupplyChainRelationshipDeliveryPlantID"`
	SupplyChainRelationshipProductionPlantID        *int                     `json:"SupplyChainRelationshipProductionPlantID"`
	Product                                         *string                  `json:"Product"`
	Buyer                                           *int                     `json:"Buyer"`
	Seller                                          *int                     `json:"Seller"`
	DeliverToParty                                  *int                     `json:"DeliverToParty"`
	DeliverToPlant                                  *string                  `json:"DeliverToPlant"`
	DeliverFromParty                                *int                     `json:"DeliverFromParty"`
	DeliverFromPlant                                *string                  `json:"DeliverFromPlant"`
	ProductionPlantBusinessPartner                  *int                     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                 *string                  `json:"ProductionPlant"`
	MRPArea                                         *string                  `json:"MRPArea"`
	MRPController                                   *string                  `json:"MRPController"`
	ProductionVersion                               *int                     `json:"ProductionVersion"`
	ProductionVersionItem                           *int                     `json:"ProductionVersionItem"`
	Sequence                                        *int                     `json:"Sequence"`
	SequenceText                                    *string                  `json:"SequenceText"`
	OperationText                                   *string                  `json:"OperationText"`
	ProductBaseUnit                                 *string                  `json:"ProductBaseUnit"`
	ProductProductionUnit                           *string                  `json:"ProductProductionUnit"`
	ProductOperationUnit                            *string                  `json:"ProductOperationUnit"`
	ProductDeliveryUnit                             *string                  `json:"ProductDeliveryUnit"`
	StandardLotSizeQuantity                         *float32                 `json:"StandardLotSizeQuantity"`
	MinimumLotSizeQuantity                          *float32                 `json:"MinimumLotSizeQuantity"`
	MaximumLotSizeQuantity                          *float32                 `json:"MaximumLotSizeQuantity"`
	OperationPlannedQuantityInBaseUnit              *float32                 `json:"OperationPlannedQuantityInBaseUnit"`
	OperationPlannedQuantityInProductionUnit        *float32                 `json:"OperationPlannedQuantityInProductionUnit"`
	OperationPlannedQuantityInOperationUnit         *float32                 `json:"OperationPlannedQuantityInOperationUnit"`
	OperationPlannedQuantityInDeliveryUnit          *float32                 `json:"OperationPlannedQuantityInDeliveryUnit"`
	OperationPlannedScrapInPercent                  *float32                 `json:"OperationPlannedScrapInPercent"`
	ResponsiblePlannerGroup                         *string                  `json:"ResponsiblePlannerGroup"`
	PlainLongText                                   *string                  `json:"PlainLongText"`
	WorkCenter                                      *int                     `json:"WorkCenter"`
	CapacityCategory                                *string                  `json:"CapacityCategory"`
	OperationCostingRelevancyType                   *string                  `json:"OperationCostingRelevancyType"`
	OperationSetupType                              *string                  `json:"OperationSetupType"`
	OperationSetupGroupCategory                     *string                  `json:"OperationSetupGroupCategory"`
	OperationSetupGroup                             *string                  `json:"OperationSetupGroup"`
	MaximumWaitDuration                             *float32                 `json:"MaximumWaitDuration"`
	StandardWaitDuration                            *float32                 `json:"StandardWaitDuration"`
	MinimumWaitDuration                             *float32                 `json:"MinimumWaitDuration"`
	WaitDurationUnit                                *string                  `json:"WaitDurationUnit"`
	MaximumQueDuration                              *float32                 `json:"MaximumQueDuration"`
	StandardQueueDuration                           *float32                 `json:"StandardQueueDuration"`
	MinimumQueueDuration                            *float32                 `json:"MinimumQueueDuration"`
	QueDurationUnit                                 *string                  `json:"QueDurationUnit"`
	MaximumMoveDuration                             *float32                 `json:"MaximumMoveDuration"`
	StandardMoveDuration                            *float32                 `json:"StandardMoveDuration"`
	MinimumMoveDuration                             *float32                 `json:"MinimumMoveDuration"`
	MoveDurationUnit                                *string                  `json:"MoveDurationUnit"`
	StandardDeliveryDuration                        *float32                 `json:"StandardDeliveryDuration"`
	StandardDeliveryDurationUnit                    *string                  `json:"StandardDeliveryDurationUnit"`
	CostElement                                     *string                  `json:"CostElement"`
	OperationErlstSchedldExecStrtDte                *string                  `json:"OperationErlstSchedldExecStrtDte"`
	OperationErlstSchedldExecStrtTme                *string                  `json:"OperationErlstSchedldExecStrtTme"`
	OperationErlstSchedldExecEndDte                 *string                  `json:"OperationErlstSchedldExecEndDte"`
	OperationErlstSchedldExecEndTme                 *string                  `json:"OperationErlstSchedldExecEndTme"`
	OperationActualExecutionStartDate               *string                  `json:"OperationActualExecutionStartDate"`
	OperationActualExecutionStartTime               *string                  `json:"OperationActualExecutionStartTime"`
	OperationActualExecutionEndDate                 *string                  `json:"OperationActualExecutionEndDate"`
	OperationActualExecutionEndTime                 *string                  `json:"OperationActualExecutionEndTime"`
	OperationConfirmedYieldQuantityInBaseUnit       *float32                 `json:"OperationConfirmedYieldQuantityInBaseUnit"`
	OperationConfirmedYieldQuantityInProductionUnit *float32                 `json:"OperationConfirmedYieldQuantityInProductionUnit"`
	OperationConfirmedYieldQuantityInOperationUnit  *float32                 `json:"OperationConfirmedYieldQuantityInOperationUnit"`
	CreationDate                                    *string                  `json:"CreationDate"`
	CreationTime                                    *string                  `json:"CreationTime"`
	LastChangeDate                                  *string                  `json:"LastChangeDate"`
	LastChangeTime                                  *string                  `json:"LastChangeTime"`
	IsReleased                                      *bool                    `json:"IsReleased"`
	IsPartiallyConfirmed                            *bool                    `json:"IsPartiallyConfirmed"`
	IsConfirmed                                     *bool                    `json:"IsConfirmed"`
	IsLocked                                        *bool                    `json:"IsLocked"`
	IsCancelled                                     *bool                    `json:"IsCancelled"`
	IsMarkedForDeletion                             *bool                    `json:"IsMarkedForDeletion"`
	ItemOperationComponent                          []ItemOperationComponent `json:"ItemOperationComponent"`
	ItemOperationCosting                            []ItemOperationCosting   `json:"ItemOperationCosting"`
}

type ItemOperationComponent struct {
	ProductionOrderConfirmation                              int      `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem                          int      `json:"ProductionOrderConfirmationItem"`
	Operations                                               int      `json:"Operations"`
	OperationsItem                                           int      `json:"OperationsItem"`
	OperationID                                              int      `json:"OperationID"`
	BillOfMaterial                                           int      `json:"BillOfMaterial"`
	BillOfMaterialItem                                       int      `json:"BillOfMaterialItem"`
	SupplyChainRelationshipID                                *int     `json:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID                        *int     `json:"SupplyChainRelationshipDeliveryID"`
	SupplyChainRelationshipDeliveryPlantID                   *int     `json:"SupplyChainRelationshipDeliveryPlantID"`
	ProductionPlantBusinessPartner                           *int     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                                          *string  `json:"ProductionPlant"`
	ComponentProduct                                         *string  `json:"ComponentProduct"`
	ComponentProductBuyer                                    *int     `json:"ComponentProductBuyer"`
	ComponentProductSeller                                   *int     `json:"ComponentProductSeller"`
	ComponentProductDeliverToParty                           *int     `json:"ComponentProductDeliverToParty"`
	ComponentProductDeliverToPlant                           *string  `json:"ComponentProductDeliverToPlant"`
	ComponentProductDeliverFromParty                         *int     `json:"ComponentProductDeliverFromParty"`
	ComponentProductDeliverFromPlant                         *string  `json:"ComponentProductDeliverFromPlant"`
	ComponentProductDeliverToPartyInOperation                *int     `json:"ComponentProductDeliverToPartyInOperation"`
	ComponentProductDeliverToPlantInOperation                *string  `json:"ComponentProductDeliverToPlantInOperation"`
	ComponentProductDeliverFromPartyInOperation              *int     `json:"ComponentProductDeliverFromPartyInOperation"`
	ComponentProductDeliverFromPlantInOperation              *string  `json:"ComponentProductDeliverFromPlantInOperation"`
	ComponentProductRequirementDateInOperation               *string  `json:"ComponentProductRequirementDateInOperation"`
	ComponentProductRequirementTimeInOperation               *string  `json:"ComponentProductRequirementTimeInOperation"`
	ComponentProductPlannedQuantityInBaseUnitInOperation     *float32 `json:"ComponentProductPlannedQuantityInBaseUnitInOperation"`
	ComponentProductPlannedQuantityInDeliveryUnitInOperation *float32 `json:"ComponentProductPlannedQuantityInDeliveryUnitInOperation"`
	ComponentProductPlannedScrapInPercentInOperation         *float32 `json:"ComponentProductPlannedScrapInPercentInOperation"`
	ComponentProductBaseUnit                                 *string  `json:"ComponentProductBaseUnit"`
	ComponentProductDeliveryUnit                             *string  `json:"ComponentProductDeliveryUnit"`
	ComponentProductIsMarkedForBackflush                     *bool    `json:"ComponentProductIsMarkedForBackflush"`
	MRPArea                                                  *string  `json:"MRPArea"`
	MRPController                                            *string  `json:"MRPController"`
	ProductionVersion                                        *int     `json:"ProductionVersion"`
	ProductionVersionItem                                    *int     `json:"ProductionVersionItem"`
	ComponentProductReservation                              *int     `json:"ComponentProductReservation"`
	ComponentProductReservationItem                          *int     `json:"ComponentProductReservationItem"`
	CreationDate                                             *string  `json:"CreationDate"`
	CreationTime                                             *string  `json:"CreationTime"`
	LastChangeDate                                           *string  `json:"LastChangeDate"`
	LastChangeTime                                           *string  `json:"LastChangeTime"`
	IsReleased                                               *bool    `json:"IsReleased"`
	IsLocked                                                 *bool    `json:"IsLocked"`
	IsCancelled                                              *bool    `json:"IsCancelled"`
	IsMarkedForDeletion                                      *bool    `json:"IsMarkedForDeletion"`
}

type ItemOperationCosting struct {
	ProductionOrderConfirmation     int      `json:"ProductionOrderConfirmation"`
	ProductionOrderConfirmationItem int      `json:"ProductionOrderConfirmationItem"`
	Operations                      int      `json:"Operations"`
	OperationsItem                  int      `json:"OperationsItem"`
	OperationsID                    int      `json:"OperationsID"`
	Currency                        *string  `json:"Currency"`
	CostingAmount                   *float32 `json:"CostingAmount"`
	CreationDate                    *string  `json:"CreationDate"`
	CreationTime                    *string  `json:"CreationTime"`
	LastChangeDate                  *string  `json:"LastChangeDate"`
	LastChangeTime                  *string  `json:"LastChangeTime"`
	IsReleased                      *bool    `json:"IsReleased"`
	IsLocked                        *bool    `json:"IsLocked"`
	IsCancelled                     *bool    `json:"IsCancelled"`
	IsMarkedForDeletion             *bool    `json:"IsMarkedForDeletion"`
}

type Partner struct {
	ProductionOrderConfirmation int     `json:"ProductionOrderConfirmation"`
	PartnerFunction             string  `json:"PartnerFunction"`
	BusinessPartner             int     `json:"BusinessPartner"`
	BusinessPartnerFullName     *string `json:"BusinessPartnerFullName"`
	BusinessPartnerName         *string `json:"BusinessPartnerName"`
	Organization                *string `json:"Organization"`
	Country                     *string `json:"Country"`
	Language                    *string `json:"Language"`
	Currency                    *string `json:"Currency"`
	ExternalDocumentID          *string `json:"ExternalDocumentID"`
	AddressID                   *int    `json:"AddressID"`
}

type Address struct {
	ProductionOrderConfirmation int    `json:"ProductionOrderConfirmation"`
	AddressID                   int    `json:"AddressID"`
	PostalCode                  string `json:"PostalCode"`
	LocalRegion                 string `json:"LocalRegion"`
	Country                     string `json:"Country"`
	District                    string `json:"District"`
	StreetName                  string `json:"StreetName"`
	CityName                    string `json:"CityName"`
	Building                    string `json:"Building"`
	Floor                       int    `json:"Floor"`
	Room                        int    `json:"Room"`
}
